<a href='http://www.scienceacademy.ca'> <img style="float: left;height:70px" src="Logo_SA.png"></a>

# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

In this lecture, we will go through the range of important NumPy's concepts and built-in function that we will be frequently using in the coming sections. As usual, this notebook is a reference to the video lecture. You can always explore this notebook if you need help.  

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>



*For complete documentation, please visit, http://www.numpy.org and a [Quickstart tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html).*

**NumPy** is extremely **important for Data Science** because:

   * Linear algebra library
   * Powerful and incredibly fast
   * Integrate C/C++ and Fortran code

Almost all of the [PyData](https://pydata.org) Eco-System libraries rely on [NumPy](http://www.numpy.org). This is one of their **most important and main building block**. In this section, we will cover the key concepts of this wonderful Python library. <br>

>***Remember, practice is a key.*** 
    
## How to install NumPy

**Installation of Python using [Anaconda Distribution](https://www.anaconda.com/download/#windows) is recommended. [This is the most popular Python Data Science platform](https://www.anaconda.com/what-is-anaconda/) with over 4.5 million users.**

If you have not installed the required package/library so far:<br>
For Anaconda users, install NumPy by going to your terminal or command prompt and typing:
    
    conda install numpy=1.11.3

If you want to use pip

    pip install numpy=1.11.3
    
**Please use the version 1.11.3 to avoid related issues, once you finish the course, you can always try other versions, they are not very different**

You do't have Anaconda and can not install it? Please visit [Numpy's official documentation on Building and installing NumPy.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)

## How to use NumPy after installation:

Now, we have installed NumPy and we want to use it, we need to import the library. The most common and official way is to import this library as "np":

    import numpy as np


#### Important Note:

<font style="font-size:12px;color:green;">* Concise information and key concepts on every topic is provided in the resource note book. At several places, you will find comments along with the code as well. **Remember**, Writing comments, while coding, is a very good practice. Comments help a lot when you come back to check your own code and you can easily recall what you have done before. Comments are specially helpful when you are working in a team on a common project.*</font>

In [1]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [2]:
# Lets create a Python list. 
my_list = [-1,0,1]
my_list, type(my_list)

([-1, 0, 1], list)

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [3]:
my_array = np.array(my_list) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [3]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

# `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [7]:
np.arange(0,10) # similar to range() in Python, not including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# We can give the step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [10]:
# start from 1 & end at 15 with 10 evenly spaced points b/w 1 to 15.
np.linspace(1, 15, 15)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.])

In [11]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ]),
 1.25)

In [12]:
np.linspace(0,15,30) # 1-D array 

array([  0.        ,   0.51724138,   1.03448276,   1.55172414,
         2.06896552,   2.5862069 ,   3.10344828,   3.62068966,
         4.13793103,   4.65517241,   5.17241379,   5.68965517,
         6.20689655,   6.72413793,   7.24137931,   7.75862069,
         8.27586207,   8.79310345,   9.31034483,   9.82758621,
        10.34482759,  10.86206897,  11.37931034,  11.89655172,
        12.4137931 ,  12.93103448,  13.44827586,  13.96551724,
        14.48275862,  15.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

### `zeros()`

* We want to create an array with **all zeros**<br>

*Press shift+tab for the documentation.*

In [13]:
np.zeros(3) # 1-D with 3 elements

array([ 0.,  0.,  0.])

In [14]:
np.zeros((4,6)) #(no_row, no_col) passing a tuple

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

### `ones()`

* We want to create an array with **all ones**<br>

*Press shift+tab for the documentation.*

In [15]:
np.ones(3)

array([ 1.,  1.,  1.])

In [16]:
np.ones((4,6)) #(no_row, no_col) passing a tuple

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

## `eye()` 
Creates an identity matrix must be a square matrix, which is useful in several linear algebra problems.
* Return a 2-D array with **ones on the diagonal and zeros elsewhere.**

*Press shift+tab for the documentation.*

In [17]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [18]:
np.random.rand(3) # 1-D array with three elements

array([ 0.2668556 ,  0.16137801,  0.65218893])

In [19]:
np.random.rand(3,2) # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[ 0.31381926,  0.34413617],
       [ 0.65349876,  0.1417028 ],
       [ 0.53881976,  0.62965666]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [20]:
np.random.randn(2)

array([ 1.39265654,  0.70478695])

In [21]:
np.random.randn(4,4) # no tuple, each dimension as a separate argument

array([[-0.19510557,  1.11071072, -1.4823238 ,  0.22163069],
       [-0.83215988,  0.89786005, -1.58374755,  0.45936113],
       [ 0.10825114,  0.28382467,  0.15052097, -0.22077727],
       [-0.18417952,  0.88135759,  0.02033709, -1.70748824]])

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100) #returns one random int, 1 inclusive, 100 exclusive

54

In [23]:
np.random.randint(1,100,10) #returns ten random int,

array([64, 20, 15, 61, 27, 15, 74, 40, 56, 89])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [24]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_ranint = np.random.randint(0,100,10)

In [25]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
array_ranint

array([71, 15, 35, 80, 78,  8, 46, 35, 81, 76])

#### `Reshape()`
Returns an array containing the same data with a new shape.

In [27]:
array_arange.reshape(4,4) # any other num will give error

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [28]:
array_ranint

array([71, 15, 35, 80, 78,  8, 46, 35, 81, 76])

In [29]:
array_ranint.max()

81

In [30]:
array_ranint.min()

8

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [31]:
array_ranint.argmax() # index starts from 0

8

In [32]:
array_ranint.argmin()

5

### Attributes
* `size, shape, dtype` 

In [33]:
# Lets take vector array, array_arange 
array_arange.shape

(16,)

In [34]:
# Size of the array 
array_arange.size

16

In [35]:
# Type of the data.
array_arange.dtype

dtype('int64')

In [36]:
# Notice the two sets of brackets
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
array_arange.reshape(4,4).shape

(4, 4)

In [38]:
array_arange.reshape(16,1).shape

(16, 1)

In [39]:
array_arange.reshape(1,16).shape

(1, 16)

In [40]:
# What is the data type of the object in the array?
array_arange.dtype

dtype('int64')

# Excellent!
### A Quick Review!
This link is worth reading!<br>
[NumPy's arrays vs Python lists](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).
