<a href='http://www.scienceacademy.ca'> <img style="float: left;height:70px" src="Logo_SA.png"></a>

# NumPy Essentials (Part: 3)
## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 3.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>


**Let's move on and create a new notebook to explore more about these concepts in NumPy.**


&#9989; *Please note that, this notebook can be considered as a reference to the video lecture. You can always come back and explore this notebook.*  



## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [1]:
# first this first, import the library
import numpy as np
# Let's create an array using arange() method
arr = np.arange(0,5)

In [2]:
# Adding two arrays
arr + arr

array([0, 2, 4, 6, 8])

In [3]:
# Subtracting two arrays
arr - arr

array([0, 0, 0, 0, 0])

In [4]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16])

In [5]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ nan,   1.,   1.,   1.,   1.])

In [6]:
1/arr
# warning for 1/0, inf

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ])

In [7]:
# Power of all the elements in an array
arr ** 2

array([ 0,  1,  4,  9, 16])

In [8]:
# Multiplication with scalar 
2 * arr

array([0, 2, 4, 6, 8])

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [9]:
# Square root
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

In [10]:
# max and min values
np.max(arr), np.min(arr)

(4, 0)

In [11]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [12]:
# Calculate the exponential (e^) of all elements in the input array 
np.exp(arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [13]:
# log function
np.log(arr)
# warning for inf

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436])

In [14]:
# Convert angles from degrees to radians
np.deg2rad(arr)

array([ 0.        ,  0.01745329,  0.03490659,  0.05235988,  0.06981317])

In [15]:
# Convert angles from radians to degrees
np.rad2deg(np.deg2rad(arr))

array([ 0.,  1.,  2.,  3.,  4.])

# Excellent Job!
### We are done with the NumPy essentials! 
### A quick review and we will move on to the exercises for practice. 