<a href='http://www.scienceacademy.ca'> <img style="float: left;height:70px" src="Logo_SA.png"></a>

# NumPy Essentials Practice Exercises Solutions:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# Please consult the lectures

**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 

In [3]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [5]:
# To avoid overwriting the output, please code here 

In [6]:
array_np = np.array(list_1)
array_np, type(array_np)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [7]:
# To avoid overwriting the output, please code here 

In [8]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [9]:
# To avoid overwriting the output, please code here 

In [10]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [11]:
# To avoid overwriting the output, please code here 

In [12]:
# Pass in a tuple, (3,4) in the built
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [13]:
# To avoid overwriting the output, please code here 

In [14]:
print(np.ones(5))

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [15]:
# To avoid overwriting the output, please code here 

In [16]:
np.ones(5) * 10

array([ 10.,  10.,  10.,  10.,  10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [17]:
# To avoid overwriting the output, please code here 

In [18]:
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [19]:
# To avoid overwriting the output, please code here 

In [20]:
np.linspace(0,1,10), np.linspace(0,1,10)[1]

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [21]:
# To avoid overwriting the output, please code here 

In [22]:
# Generating vector array
vector_array = np.arange(25)
vector_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
# To avoid overwriting the output, please code here 

In [24]:
# reshape to convert into 2-d
matrix_array = vector_array.reshape(5,5)
matrix_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 

In [26]:
# Using shape
vector_array.shape = (5,5)
vector_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [27]:
# To avoid overwriting the output, please code here 

In [28]:
np.arange(1,26).reshape(5,5) / 10

array([[ 0.1,  0.2,  0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5],
       [ 1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [29]:
# To avoid overwriting the output, please code here 

In [30]:
print(np.linspace(0, 24, 25).reshape(5,5))
print("Step size is: ",np.linspace(0, 24, 25)[1])

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]
Step size is:  1.0


**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random number using NumPy built-in function?**

In [32]:
# To avoid overwriting the output, please code here 

In [33]:
np.random.rand(1)

array([ 0.55509608])

**16. Write a code to generate a 7x5 matrix of 35 random numbers?** <br>
*Notice, there are no ( ) in the output matrix!*

In [34]:
# To avoid overwriting the output, please code here 

In [35]:
print(np.random.rand(7,5))
# np.random.rand(35).reshape(7,5) # this will also work

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [36]:
# To avoid overwriting the output, please code here 

In [37]:
np.eye(5)*5

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

**18. Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [38]:
#18a:
# To avoid overwriting the output, please code here 

In [39]:
array_2d= np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [40]:
#18b:
# To avoid overwriting the output, please code here 

In [41]:
array_2d[3:,2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [42]:
#18c:
# To avoid overwriting the output, please code here 

In [43]:
array_2d[5,4]

29

In [44]:
#18d:
# To avoid overwriting the output, please code here 

In [45]:
array_2d[:3,1:2] # array_2d[:3,1:3] for col 1 and 2 

array([[ 1],
       [ 6],
       [11]])

In [46]:
#18e:
# To avoid overwriting the output, please code here 

In [47]:
array_2d[2,:] # array_2d[2:3,:] will give the same output

array([10, 11, 12, 13, 14])

In [48]:
#18f:
# To avoid overwriting the output, please code here 

In [49]:
array_2d[2:4,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**19. Can you calculate the sum of all the numbers in array_2d?**

In [50]:
# To avoid overwriting the output, please code here 

In [51]:
array_2d.sum()

435

**20. Calculate sum of all the rows and columns in array_2d.**

In [52]:
# To avoid overwriting the output, please code here 

In [53]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


**21. Calculate the standard deviation of the values in array_2d.**

In [54]:
# To avoid overwriting the output, please code here 

In [55]:
array_2d.std()

8.6554414483991895

**22. Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [56]:
# To avoid overwriting the output, please code here 

In [57]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 